export const PATH = {
    INDEX: '/',
    LOGIN: '/login',
    NOT_FOUND: '404',
    ADD: 'add',
    SUB: 'sub',
    PARENT: 'parent',
    DISENABLE: "disenable",
    PRODUCTS: 'products',
    UPDATE_PRODUCTS: ':sku',
    CATEGORIES: 'categories',
    WAREHOUSES: 'warehouses',
    SIZES: 'sizes',
    COUPONS: 'coupons',
    ORDERS: 'orders',
    UNCONFIMRED: 'unconfimred',
    ACCOMPLISHED: 'accomplished',
    UNACCOMPLISHED: 'unaccomplished',
    ORDERS_DETAILS: 'details/:code',
    DELIVERY: 'delivery',
    USER: 'user',
    USER_DETAILS: ':email',
    CHILDREN: '/*',
}


export const PATH_API = {
    PARAMS: '?',
    LOGIN: 'auth/login',
    STATUS: '/status',
    STATUSES: '/statuses',
    SEARCH: "/search",
    SELECT: "/select",
    CHECKBOX: "/checkbox",
    RADIO: "/radio",
    SELECTED_DISENABLE: '/selected/disenable',
    SELECTED_ENABLED: '/selected/enabled',
    SELECTED_PARENT: '/selected/parent',
    SELECTED_SUB: '/selected/sub',
    SELECTED_DELETE: '/selected/delete',
    PROVINCES: '/provinces',
    DISTRICTS: '/districts',
    WARD: '/ward',
    GENDER: '/gender',
    SUB: "/sub",
    PARENT: "/parent",
    DISENABLE: "/disenable",
    ENABLED: "/enabled",
    USERS: "/users",
    ROLES: "/roles",
    PRODUCTS: "/products",
    CATEGORIES: "/categories",
    CATEGORY: "/category",
    WAREHOUSES: '/warehouses',
    COUPONS: '/coupons',
    SIZES: "/sizes",
    ORDERS: '/orders',
    ORDER: '/order',
    PAYMENT: '/payment',
    DELIVERY: '/delivery',
    UNCONFIMRED: '/unconfimred',
    UNACCOMPLISHED: '/unaccomplished',
    ACCOMPLISHED: '/accomplished',
    CONFIRMATION: '/confirmation',
    STATE_TRANSTION: "/state/transtion"
}

export const PATH_MATCH = {
    ADD_MATCH_NAME: '/add/match/name/',
    ADD_MATCH_SKU: '/add/match/sku/',
    ADD_MATCH_CODE: '/add/match/code/',
    ADD_MATCH_EMAIL: '/add/match/email/',
    ADD_MATCH_PHONE: '/add/match/phone/',
    UPDATE_MATCH_NAME: '/update/match/name/',
    UPDATE_MATCH_SKU: '/update/match/sku/',
    UPDATE_MATCH_CODE: '/update/match/code/',
    UPDATE_MATCH_PHONE: '/update/match/phone/',
}