export { default as ProductRoutes } from './product/index';
export { default as CategoryRoutes } from './category/index';
export { default as SizeRoutes } from './size/index';
export { default as CouponRoutes } from './coupon/index';
export { default as ProductSizeRoutes } from './productSize/index';
export { default as OrderRoutes } from './order/index';
export { default as DeliveryRoutes } from './delivery/index';
export { default as UserRoutes } from './user/index';
export { default as WarehouseRoutes } from './warehouse/index';